// <auto-generated />
namespace website_emp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class databaseversion4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(databaseversion4));
        
        string IMigrationMetadata.Id
        {
            get { return "202001091026521_databaseversion4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
